---
- hosts: servers
  roles:
    - local.devserver
    - geerlingguy.mysql
  become: true

  vars:
    mysql_packages:
      - mariadb-client
      - mariadb-server

    mysql_sql_mode: "TRADITIONAL"