---
- name: Set hostname.
  hostname:
    name: "{{ inventory_hostname_short }}" 
  when: ansible_hostname != inventory_hostname_short

- name: Adjust GPU memory.
  lineinfile:
    path: /boot/config.txt
    regexp: ^gpu_mem
    line: gpu_mem=16

- name: Set keyboard layout.
  lineinfile:
    path: /etc/default/keyboard
    regexp: ^XKBLAYOUT 
    line: XKBLAYOUT="se"

- name: Set timezone.
  timezone:
    name: Europe/Stockholm

