---
# tasks file for local.devserver
- name: Add dependencies.
  apt:
    name:
      - apache2
      - php
      - php-mysql
      - libapache2-mod-php
      - emacs-nox
      - php-elisp 
      - libmysqlclient-dev
      - python3-pip
      - unzip
    state: latest
  notify: Restart Apache

- name: Autoupgrade pip.
  shell: 'pip3 install --upgrade pip'

- name: Add Python dependencies.
  pip:
    name: mysqlclient
    state: present

- name: Enable mod_rewrite
  command: a2enmod rewrite
  notify: Restart Apache
